'\" t
.\"     Title: LXAPPEARANCE
.\"    Author: Ying-Chun Liu
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: April  20, 2008
.\"    Manual: http://LXDE.org
.\"    Source: http://LXDE.org
.\"  Language: English
.\"
.TH "LXAPPEARANCE" "1" "April 20, 2008" "http://LXDE\&.org" "http://LXDE.org"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lxappearance \- GTK+ theme switcher
.SH "SYNOPSIS"
.HP \w'\fBlxappearance\fR\ 'u
\fBlxappearance\fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBlxappearance\fR
command\&.
.PP
\fBlxappearance\fR
is a program to change GTK+ themes, icon themes, and fonts used by applications\&. It is a feature\-rich GTK+ theme switcher\&.
.SH "AUTHOR"
.PP
This manual page was written by paulliu
<grandpaul@gmail\&.com>
for the
Debian
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.PP
The source code of this manual page should be in
\&.sgml
format\&. It is better not to modify the
\&.1
file directly\&.
.SH "AUTHOR"
.PP
\fBYing\-Chun Liu\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2008 paulliu
.br
