/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "demo.h"
#include "demo-ui.h"
#include "glade-support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_demo_window (void)
{
  GtkWidget *demo_window;
  GtkWidget *top_vbox;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *handlebox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolbutton1;
  GtkWidget *toolbutton2;
  GtkWidget *toolbutton3;
  GtkWidget *notebook2;
  GtkWidget *scrolledwindow4;
  GtkWidget *icon_view;
  GtkWidget *label12;
  GtkWidget *hbox2;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *vbox6;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *hseparator1;
  GtkWidget *checkbutton1;
  GtkWidget *entry1;
  GtkWidget *label16;
  GtkWidget *vbox7;
  GtkWidget *progressbar1;
  GtkWidget *hscale1;
  GtkWidget *hbox3;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *button1;
  GtkWidget *combobox2;
  GtkWidget *label13;
  GtkWidget *scrolledwindow5;
  GtkWidget *text_view;
  GtkWidget *label14;
  GtkWidget *scrolledwindow6;
  GtkWidget *demo_treeview;
  GtkWidget *label17;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();
/*
  demo_window = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_events (demo_window, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_window_set_decorated (GTK_WINDOW (demo_window), FALSE);
*/
  top_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (top_vbox);
  demo_window = top_vbox;

/*
  gtk_container_add (GTK_CONTAINER (demo_window), top_vbox);
*/

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (top_vbox), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), delete1);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_image_menu_item_new_from_stock ("gtk-about", accel_group);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (top_vbox), handlebox1, FALSE, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  gtk_toolbar_set_show_arrow (GTK_TOOLBAR (toolbar1), FALSE);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolbutton1 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-go-back");
  gtk_widget_show (toolbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton1);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton1), tooltips, _("Back"), NULL);

  toolbutton2 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-go-forward");
  gtk_widget_show (toolbutton2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton2);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton2), tooltips, _("Forward"), NULL);

  toolbutton3 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-stop");
  gtk_widget_show (toolbutton3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton3);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton3), tooltips, _("Stop"), NULL);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (top_vbox), notebook2, TRUE, TRUE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  icon_view = gtk_icon_view_new ();
  gtk_widget_show (icon_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), icon_view);

  label12 = gtk_label_new (_("Tab1"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label12);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (notebook2), hbox2);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox2), frame2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 4);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 4, 4, 0);

  vbox6 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox6);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Radio Button"));
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (vbox6), radiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Radio Button"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (vbox6), radiobutton2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox6), hseparator1, FALSE, TRUE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Check Button"));
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (vbox6), checkbutton1, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox6), entry1, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 9679);

  label16 = gtk_label_new (_("Demo"));
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 4);

  progressbar1 = gtk_progress_bar_new ();
  gtk_widget_show (progressbar1);
  gtk_box_pack_start (GTK_BOX (vbox7), progressbar1, FALSE, FALSE, 0);
  gtk_progress_bar_set_fraction (GTK_PROGRESS_BAR (progressbar1), 0.6);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (progressbar1), "60 %");

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_show (hscale1);
  gtk_box_pack_start (GTK_BOX (vbox7), hscale1, FALSE, TRUE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox3, FALSE, TRUE, 0);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (hbox3), spinbutton1, TRUE, TRUE, 0);

  button1 = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox3), button1, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_box_pack_start (GTK_BOX (vbox7), combobox2, FALSE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Test Item 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Test Item 2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Test Item 3"));

  label13 = gtk_label_new (_("Tab2"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label13);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  text_view = gtk_text_view_new ();
  gtk_widget_show (text_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), text_view);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text_view)), _("Type some characters here to test currently selected font."), -1);

  label14 = gtk_label_new (_("Tab3"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label14);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow6);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_SHADOW_IN);

  demo_treeview = gtk_tree_view_new ();
  gtk_widget_show (demo_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), demo_treeview);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (demo_treeview), TRUE);

  label17 = gtk_label_new (_("Tab4"));
  gtk_widget_show (label17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label17);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (top_vbox), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) top_vbox, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */

/*
  GLADE_HOOKUP_OBJECT_NO_REF (demo_window, demo_window, "demo_window");
  GLADE_HOOKUP_OBJECT (demo_window, top_vbox, "top_vbox");
  GLADE_HOOKUP_OBJECT (demo_window, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (demo_window, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (demo_window, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (demo_window, new1, "new1");
  GLADE_HOOKUP_OBJECT (demo_window, open1, "open1");
  GLADE_HOOKUP_OBJECT (demo_window, save1, "save1");
  GLADE_HOOKUP_OBJECT (demo_window, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (demo_window, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (demo_window, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (demo_window, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (demo_window, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (demo_window, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (demo_window, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (demo_window, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (demo_window, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (demo_window, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (demo_window, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (demo_window, about1, "about1");
  GLADE_HOOKUP_OBJECT (demo_window, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (demo_window, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (demo_window, toolbutton1, "toolbutton1");
  GLADE_HOOKUP_OBJECT (demo_window, toolbutton2, "toolbutton2");
  GLADE_HOOKUP_OBJECT (demo_window, toolbutton3, "toolbutton3");
  GLADE_HOOKUP_OBJECT (demo_window, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (demo_window, scrolledwindow4, "scrolledwindow4");
*/
  GLADE_HOOKUP_OBJECT (demo_window, icon_view, "icon_view");
/*
  GLADE_HOOKUP_OBJECT (demo_window, label12, "label12");
  GLADE_HOOKUP_OBJECT (demo_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (demo_window, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (demo_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (demo_window, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (demo_window, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (demo_window, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (demo_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (demo_window, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (demo_window, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (demo_window, label16, "label16");
  GLADE_HOOKUP_OBJECT (demo_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (demo_window, progressbar1, "progressbar1");
  GLADE_HOOKUP_OBJECT (demo_window, hscale1, "hscale1");
  GLADE_HOOKUP_OBJECT (demo_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (demo_window, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (demo_window, button1, "button1");
  GLADE_HOOKUP_OBJECT (demo_window, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (demo_window, label13, "label13");
  GLADE_HOOKUP_OBJECT (demo_window, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (demo_window, text_view, "text_view");
  GLADE_HOOKUP_OBJECT (demo_window, label14, "label14");
  GLADE_HOOKUP_OBJECT (demo_window, scrolledwindow6, "scrolledwindow6");
*/
  GLADE_HOOKUP_OBJECT (demo_window, demo_treeview, "demo_treeview");
/*
  GLADE_HOOKUP_OBJECT (demo_window, label17, "label17");
  GLADE_HOOKUP_OBJECT (demo_window, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (demo_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (demo_window), accel_group);
*/
  return demo_window;
}

