/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "main-dlg.h"
#include "main-dlg-ui.h"
#include "glade-support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dlg (void)
{
  GtkWidget *dlg;
  GtkWidget *dialog_vbox1;
  GtkWidget *hbox1;
  GtkWidget *notebook1;
  GtkWidget *vbox4;
  GtkWidget *label8;
  GtkWidget *scrolledwindow1;
  GtkWidget *gtk_theme_view;
  GtkWidget *label2;
  GtkWidget *vbox3;
  GtkWidget *label7;
  GtkWidget *scrolledwindow2;
  GtkWidget *icon_theme_view;
  GtkWidget *label3;
  GtkWidget *vbox2;
  GtkWidget *label6;
  GtkWidget *scrolledwindow3;
  GtkWidget *font_view;
  GtkWidget *table1;
  GtkWidget *label9;
  GtkWidget *comboboxentry1;
  GtkWidget *label10;
  GtkWidget *combobox1;
  GtkWidget *label4;
  GtkWidget *empty_notebook_page;
  GtkWidget *label5;
  GtkWidget *vbox1;
  GtkWidget *label15;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *vbox5;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolbutton1;
  GtkWidget *toolbutton2;
  GtkWidget *toolbutton3;
  GtkWidget *notebook2;
  GtkWidget *scrolledwindow4;
  GtkWidget *icon_view;
  GtkWidget *label12;
  GtkWidget *hbox2;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *vbox6;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *hseparator1;
  GtkWidget *checkbutton1;
  GtkWidget *entry1;
  GtkWidget *label16;
  GtkWidget *vbox7;
  GtkWidget *progressbar1;
  GtkWidget *hscale1;
  GtkWidget *hbox3;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *button1;
  GtkWidget *combobox2;
  GtkWidget *label13;
  GtkWidget *scrolledwindow5;
  GtkWidget *text_view;
  GtkWidget *label14;
  GtkWidget *statusbar1;
  GtkWidget *dialog_action_area1;
  GtkWidget *apply;
  GtkWidget *closebutton1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  dlg = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dlg), _("Appearance Settings"));
  gtk_window_set_type_hint (GTK_WINDOW (dlg), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dlg)->vbox;
  gtk_widget_show (dialog_vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), hbox1, TRUE, TRUE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (hbox1), notebook1, FALSE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox4);

  label8 = gtk_label_new (_("Available Window Themes"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox4), label8, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  gtk_theme_view = gtk_tree_view_new ();
  gtk_widget_show (gtk_theme_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), gtk_theme_view);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (gtk_theme_view), FALSE);

  label2 = gtk_label_new (_("Window"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);

  label7 = gtk_label_new (_("Available Icon Themes"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (vbox3), label7, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  icon_theme_view = gtk_tree_view_new ();
  gtk_widget_show (icon_theme_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), icon_theme_view);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (icon_theme_view), FALSE);

  label3 = gtk_label_new (_("Icon"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label3);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  label6 = gtk_label_new (_("Available Fonts"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox2), label6, FALSE, FALSE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  font_view = gtk_tree_view_new ();
  gtk_widget_show (font_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), font_view);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (font_view), FALSE);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, FALSE, TRUE, 0);

  label9 = gtk_label_new (_("Font Size:"));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_table_attach (GTK_TABLE (table1), comboboxentry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (comboboxentry1, 48, -1);

  label10 = gtk_label_new (_("Style:"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_table_attach (GTK_TABLE (table1), combobox1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label4 = gtk_label_new (_("Font"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label4);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label5 = gtk_label_new (_("Other"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label5);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox1, TRUE, TRUE, 0);

  label15 = gtk_label_new (_("<b>Preview</b>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (vbox1), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 6);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 4, 4);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox5);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox5), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), delete1);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_image_menu_item_new_from_stock ("gtk-about", accel_group);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox5), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  gtk_toolbar_set_show_arrow (GTK_TOOLBAR (toolbar1), FALSE);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolbutton1 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-go-back");
  gtk_widget_show (toolbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton1);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton1), tooltips, _("Back"), NULL);

  toolbutton2 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-go-forward");
  gtk_widget_show (toolbutton2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton2);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton2), tooltips, _("Forward"), NULL);

  toolbutton3 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-stop");
  gtk_widget_show (toolbutton3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton3);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton3), tooltips, _("Stop"), NULL);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (vbox5), notebook2, TRUE, TRUE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  icon_view = gtk_icon_view_new ();
  gtk_widget_show (icon_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), icon_view);

  label12 = gtk_label_new (_("Tab1"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label12);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (notebook2), hbox2);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox2), frame2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 4);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 4, 4, 0);

  vbox6 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox6);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Radio Button"));
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (vbox6), radiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Radio Button"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (vbox6), radiobutton2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox6), hseparator1, FALSE, TRUE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Check Button"));
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (vbox6), checkbutton1, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox6), entry1, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 9679);

  label16 = gtk_label_new (_("Demo"));
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 4);

  progressbar1 = gtk_progress_bar_new ();
  gtk_widget_show (progressbar1);
  gtk_box_pack_start (GTK_BOX (vbox7), progressbar1, FALSE, FALSE, 0);
  gtk_progress_bar_set_fraction (GTK_PROGRESS_BAR (progressbar1), 0.6);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (progressbar1), "60 %");

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_show (hscale1);
  gtk_box_pack_start (GTK_BOX (vbox7), hscale1, FALSE, TRUE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox3, FALSE, TRUE, 0);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (hbox3), spinbutton1, TRUE, TRUE, 0);

  button1 = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox3), button1, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_box_pack_start (GTK_BOX (vbox7), combobox2, FALSE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Test Item 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Test Item 2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Test Item 3"));

  label13 = gtk_label_new (_("Tab2"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label13);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  text_view = gtk_text_view_new ();
  gtk_widget_show (text_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), text_view);

  label14 = gtk_label_new (_("Tab3"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label14);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox5), statusbar1, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (dlg)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  apply = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (apply);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlg), apply, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (apply, GTK_CAN_DEFAULT);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlg), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) dlg, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) apply, "clicked",
                    G_CALLBACK (on_apply_clicked),
                    NULL);
  g_signal_connect ((gpointer) closebutton1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlg, dlg, "dlg");
  GLADE_HOOKUP_OBJECT_NO_REF (dlg, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dlg, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (dlg, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (dlg, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dlg, label8, "label8");
  GLADE_HOOKUP_OBJECT (dlg, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (dlg, gtk_theme_view, "gtk_theme_view");
  GLADE_HOOKUP_OBJECT (dlg, label2, "label2");
  GLADE_HOOKUP_OBJECT (dlg, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (dlg, label7, "label7");
  GLADE_HOOKUP_OBJECT (dlg, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (dlg, icon_theme_view, "icon_theme_view");
  GLADE_HOOKUP_OBJECT (dlg, label3, "label3");
  GLADE_HOOKUP_OBJECT (dlg, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (dlg, label6, "label6");
  GLADE_HOOKUP_OBJECT (dlg, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (dlg, font_view, "font_view");
  GLADE_HOOKUP_OBJECT (dlg, table1, "table1");
  GLADE_HOOKUP_OBJECT (dlg, label9, "label9");
  GLADE_HOOKUP_OBJECT (dlg, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (dlg, label10, "label10");
  GLADE_HOOKUP_OBJECT (dlg, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (dlg, label4, "label4");
  GLADE_HOOKUP_OBJECT (dlg, label5, "label5");
  GLADE_HOOKUP_OBJECT (dlg, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (dlg, label15, "label15");
  GLADE_HOOKUP_OBJECT (dlg, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (dlg, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (dlg, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (dlg, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (dlg, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (dlg, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (dlg, new1, "new1");
  GLADE_HOOKUP_OBJECT (dlg, open1, "open1");
  GLADE_HOOKUP_OBJECT (dlg, save1, "save1");
  GLADE_HOOKUP_OBJECT (dlg, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (dlg, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (dlg, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (dlg, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (dlg, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (dlg, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (dlg, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (dlg, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (dlg, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (dlg, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (dlg, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (dlg, about1, "about1");
  GLADE_HOOKUP_OBJECT (dlg, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (dlg, toolbutton1, "toolbutton1");
  GLADE_HOOKUP_OBJECT (dlg, toolbutton2, "toolbutton2");
  GLADE_HOOKUP_OBJECT (dlg, toolbutton3, "toolbutton3");
  GLADE_HOOKUP_OBJECT (dlg, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (dlg, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (dlg, icon_view, "icon_view");
  GLADE_HOOKUP_OBJECT (dlg, label12, "label12");
  GLADE_HOOKUP_OBJECT (dlg, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (dlg, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (dlg, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (dlg, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (dlg, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (dlg, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (dlg, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (dlg, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (dlg, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (dlg, label16, "label16");
  GLADE_HOOKUP_OBJECT (dlg, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (dlg, progressbar1, "progressbar1");
  GLADE_HOOKUP_OBJECT (dlg, hscale1, "hscale1");
  GLADE_HOOKUP_OBJECT (dlg, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (dlg, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (dlg, button1, "button1");
  GLADE_HOOKUP_OBJECT (dlg, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (dlg, label13, "label13");
  GLADE_HOOKUP_OBJECT (dlg, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (dlg, text_view, "text_view");
  GLADE_HOOKUP_OBJECT (dlg, label14, "label14");
  GLADE_HOOKUP_OBJECT (dlg, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (dlg, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dlg, apply, "apply");
  GLADE_HOOKUP_OBJECT (dlg, closebutton1, "closebutton1");
  GLADE_HOOKUP_OBJECT_NO_REF (dlg, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (dlg), accel_group);

  return dlg;
}

